[project]
name = "hash-calculation"
version = "0.0.3-1"
description = "Calculate file hashes super fast!"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alive-progress>=3.3.0",
    "questionary>=2.1.1",
]

[project.scripts]
hashcalc = "hash_calculation.__main__:main"
